// src/components/selector.tsx
import { useState, useMemo, useCallback } from 'react'
import { Box, Text, useInput } from 'ink'
import pc from 'picocolors'
import type { RepoGroup } from '../utils/repos'
import { toTildePath } from '../utils/format'

// --- Types ---

type SelectorState = 'list' | 'search' | 'succeed' | 'error'

type ListItem = {
  type: 'root' | 'owner' | 'repo' | 'blank'
  label: string
  path: string
  owner?: string
  selectable: boolean
}

type SearchItem = {
  type: 'project' | 'owner'
  label: string
  owner?: string
  path: string
  selectable: boolean
}

type SelectorProps = {
  root: string
  groups: RepoGroup[]
  onSelect: (path: string) => void
  onCancel: () => void
}

// --- Constants ---

const LIST_HEIGHT = 15
const POINTER = '\u276F '
const POINTER_BLANK = '  '
const QUESTION = 'Where would you like to go? '

// --- List building ---

function buildListItems(root: string, groups: RepoGroup[]): ListItem[] {
  const items: ListItem[] = []

  // Root item
  items.push({
    type: 'root',
    label: '<root>',
    path: root,
    selectable: true,
  })

  for (const group of groups) {
    // Blank separator
    items.push({ type: 'blank', label: '', path: '', selectable: false })

    // Owner header
    items.push({
      type: 'owner',
      label: group.owner,
      path: group.path,
      owner: group.owner,
      selectable: true,
    })

    // Repos
    for (const repo of group.repos) {
      items.push({
        type: 'repo',
        label: repo.name,
        path: repo.path,
        owner: group.owner,
        selectable: true,
      })
    }
  }

  return items
}

// --- Search ---

function searchItems(query: string, groups: RepoGroup[], root: string): SearchItem[] {
  const q = query.toLowerCase()
  const items: SearchItem[] = []
  const matchedOwners = new Set<string>()

  // Search projects - only match by project name
  // Score: 0 = exact match, 1 = prefix match, 2 = substring match
  const projectMatches: Array<{ score: number; item: SearchItem }> = []
  for (const group of groups) {
    for (const repo of group.repos) {
      const name = repo.name.toLowerCase()
      if (!name.includes(q)) continue
      const score = name === q ? 0 : name.startsWith(q) ? 1 : 2
      projectMatches.push({
        score,
        item: {
          type: 'project',
          label: repo.name,
          owner: repo.owner,
          path: repo.path,
          selectable: true,
        },
      })
      matchedOwners.add(repo.owner)
    }
  }
  projectMatches.sort((a, b) => a.score - b.score || a.item.label.length - b.item.label.length)

  const sortedProjects: SearchItem[] = projectMatches.map((m) => m.item)

  // Root match - exact match gets score 0, prefix score 1, substring score 2
  if ('<root>'.includes(q)) {
    const rootScore = '<root>' === q ? 0 : '<root>'.startsWith(q) ? 1 : 2
    const rootItem: SearchItem = { type: 'project', label: '<root>', path: root, selectable: true }
    const insertIdx = sortedProjects.findIndex(
      (_, i) => (projectMatches[i]?.score ?? 3) > rootScore,
    )
    if (insertIdx === -1) sortedProjects.push(rootItem)
    else sortedProjects.splice(insertIdx, 0, rootItem)
  }

  items.push(...sortedProjects)

  // Search owners
  const ownerMatches: SearchItem[] = []
  for (const group of groups) {
    if (group.owner.toLowerCase().includes(q) || matchedOwners.has(group.owner)) {
      ownerMatches.push({
        type: 'owner',
        label: group.owner,
        path: group.path,
        selectable: true,
      })
    }
  }

  if (ownerMatches.length && sortedProjects.length) {
    // Blank separator
    items.push({
      type: 'owner',
      label: '',
      path: '',
      selectable: false,
    })
  }

  items.push(...ownerMatches)

  return items
}

function highlightMatch(text: string, query: string, baseColor: (s: string) => string): string {
  if (!query) return baseColor(text)
  const lower = text.toLowerCase()
  const qLower = query.toLowerCase()
  const idx = lower.indexOf(qLower)
  if (idx === -1) return baseColor(text)

  const before = text.slice(0, idx)
  const match = text.slice(idx, idx + query.length)
  const after = text.slice(idx + query.length)
  return baseColor(before) + pc.bold(pc.green(match)) + baseColor(after)
}

// --- Scroll logic ---

function computeScroll(cursorIndex: number, totalItems: number, height: number): number {
  if (totalItems <= height) return 0
  // Center the cursor
  let start = cursorIndex - Math.floor(height / 2)
  start = Math.max(0, start)
  start = Math.min(start, totalItems - height)
  return start
}

// --- Components ---

function Header({
  state,
  query,
  selectedPath,
  errorMessage,
}: {
  state: SelectorState
  query: string
  selectedPath: string
  errorMessage: string
}) {
  let icon = '?'
  let content = ''

  if (state === 'succeed') {
    icon = pc.green('\u2713')
    content = pc.bold(QUESTION) + pc.cyan(toTildePath(selectedPath))
  } else if (state === 'error') {
    icon = pc.red('\u2717')
    content = pc.bold(pc.red(errorMessage))
  } else {
    icon = pc.yellow('?')
    content = pc.bold(QUESTION) + query
  }

  return <Text>{`${icon} ${content}`}</Text>
}

function ListModeView({
  items,
  cursorIndex,
  scrollOffset,
  height,
}: {
  items: ListItem[]
  cursorIndex: number
  scrollOffset: number
  height: number
}) {
  // Find sticky owner: look backward from scrollOffset for the current group's owner
  let stickyOwner: ListItem | null = null
  if (scrollOffset > 0) {
    for (let i = scrollOffset - 1; i >= 0; i--) {
      if (items[i].type === 'owner') {
        // Check if the owner's group extends into the visible area
        stickyOwner = items[i]
        break
      }
      if (items[i].type === 'blank' && i < scrollOffset) {
        // We passed a group boundary without finding an owner above
        break
      }
    }
    // Verify the sticky owner's group is still visible
    if (stickyOwner) {
      let groupEnd = items.indexOf(stickyOwner) + 1
      while (groupEnd < items.length && items[groupEnd].type !== 'blank') {
        groupEnd++
      }
      if (groupEnd <= scrollOffset) {
        stickyOwner = null
      }
    }
  }

  // If the owner header is already visible in the viewport, don't show sticky
  if (stickyOwner) {
    const ownerIdx = items.indexOf(stickyOwner)
    if (ownerIdx >= scrollOffset && ownerIdx < scrollOffset + height) {
      stickyOwner = null
    }
  }

  const adjustedHeight = stickyOwner ? height - 1 : height
  const displayStart = stickyOwner ? scrollOffset + 1 : scrollOffset
  const displayItems = items.slice(displayStart, displayStart + adjustedHeight)

  const lines: string[] = []

  if (stickyOwner) {
    const isSelected = items.indexOf(stickyOwner) === cursorIndex
    const prefix = isSelected ? POINTER : POINTER_BLANK
    lines.push(prefix + pc.bold(pc.cyan(stickyOwner.label)))
  }

  for (let i = 0; i < displayItems.length; i++) {
    const item = displayItems[i]
    const actualIndex = displayStart + i
    const isSelected = actualIndex === cursorIndex

    if (item.type === 'blank') {
      lines.push('')
      continue
    }

    const prefix = isSelected ? POINTER : POINTER_BLANK

    if (item.type === 'owner') {
      const text = isSelected ? pc.underline(pc.green(item.label)) : pc.bold(pc.cyan(item.label))
      lines.push(prefix + text)
    } else {
      const text = isSelected ? pc.underline(pc.green(item.label)) : item.label
      lines.push(prefix + text)
    }
  }

  return <Text>{lines.join('\n')}</Text>
}

function SearchModeView({
  items,
  cursorIndex,
  scrollOffset,
  height,
  query,
}: {
  items: SearchItem[]
  cursorIndex: number
  scrollOffset: number
  height: number
  query: string
}) {
  const visibleItems = items.slice(scrollOffset, scrollOffset + height)
  const lines: string[] = []

  for (let i = 0; i < visibleItems.length; i++) {
    const item = visibleItems[i]
    const actualIndex = scrollOffset + i
    const isSelected = actualIndex === cursorIndex

    if (!item.selectable) {
      lines.push('')
      continue
    }

    const prefix = isSelected ? POINTER : POINTER_BLANK

    if (item.type === 'project') {
      if (isSelected) {
        const name = pc.underline(pc.green(item.label))
        const suffix = item.owner ? pc.dim(` (${item.owner})`) : ''
        lines.push(prefix + name + suffix)
      } else {
        const name = highlightMatch(item.label, query, (s) => s)
        const suffix = item.owner ? pc.dim(` (${item.owner})`) : ''
        lines.push(prefix + name + suffix)
      }
    } else {
      if (isSelected) {
        lines.push(prefix + pc.underline(pc.green(item.label)))
      } else {
        lines.push(prefix + highlightMatch(item.label, query, pc.gray))
      }
    }
  }

  return <Text>{lines.join('\n')}</Text>
}

function Footer({ path: footerPath, noMatch }: { path: string; noMatch: boolean }) {
  const text = noMatch
    ? pc.dim(pc.italic('No directory found'))
    : pc.dim('Path: ') + pc.gray(toTildePath(footerPath))
  return (
    <Box marginTop={1}>
      <Text>{text}</Text>
    </Box>
  )
}

// --- Main Selector ---

export function Selector({ root, groups, onSelect, onCancel }: SelectorProps) {
  const [state, setState] = useState<SelectorState>('list')
  const [query, setQuery] = useState('')
  const [cursorIndex, setCursorIndex] = useState(0)
  const [selectedPath, setSelectedPath] = useState('')
  const [errorMessage, setErrorMessage] = useState('')

  const listItems = useMemo(() => buildListItems(root, groups), [root, groups])
  const searchResults = useMemo(
    () => (query ? searchItems(query, groups, root) : []),
    [query, groups, root],
  )

  const isSearchMode = query.length > 0
  const currentItems = isSearchMode ? searchResults : listItems
  const selectableIndices = useMemo(
    () => currentItems.map((item, i) => (item.selectable ? i : -1)).filter((i) => i !== -1),
    [currentItems],
  )

  const scrollOffset = useMemo(
    () => computeScroll(cursorIndex, currentItems.length, LIST_HEIGHT),
    [cursorIndex, currentItems.length],
  )

  const currentPath = useMemo(() => {
    if (!selectableIndices.length) return ''
    const item = currentItems[cursorIndex]
    return item?.path || ''
  }, [currentItems, cursorIndex, selectableIndices])

  const moveCursor = useCallback(
    (direction: 1 | -1) => {
      if (!selectableIndices.length) return
      const currentSelIdx = selectableIndices.indexOf(cursorIndex)
      let nextSelIdx = currentSelIdx + direction
      if (nextSelIdx < 0) nextSelIdx = selectableIndices.length - 1
      if (nextSelIdx >= selectableIndices.length) nextSelIdx = 0
      setCursorIndex(selectableIndices[nextSelIdx])
    },
    [selectableIndices, cursorIndex],
  )

  // Reset cursor when switching modes or query changes
  const resetCursor = useCallback((items: Array<{ selectable: boolean }>) => {
    const firstSelectable = items.findIndex((item) => item.selectable)
    setCursorIndex(firstSelectable >= 0 ? firstSelectable : 0)
  }, [])

  useInput((input, key) => {
    if (state === 'succeed' || state === 'error') return

    // Cancel
    if (key.ctrl && input === 'c') {
      setState('error')
      setErrorMessage('Canceled.')
      onCancel()
      return
    }

    // Escape - clear search or cancel
    if (key.escape) {
      if (query) {
        setQuery('')
        resetCursor(listItems)
      } else {
        setState('error')
        setErrorMessage('Canceled.')
        onCancel()
      }
      return
    }

    // Submit
    if (key.return) {
      if (currentPath) {
        setState('succeed')
        setSelectedPath(currentPath)
        onSelect(currentPath)
      }
      return
    }

    // Navigation
    if (key.upArrow) {
      moveCursor(-1)
      return
    }
    if (key.downArrow) {
      moveCursor(1)
      return
    }

    // Tab handling - ignore
    if (key.tab) return

    // Backspace
    if (key.backspace || key.delete) {
      const newQuery = query.slice(0, -1)
      setQuery(newQuery)
      if (newQuery) {
        const newResults = searchItems(newQuery, groups, root)
        resetCursor(newResults)
      } else {
        resetCursor(listItems)
      }
      return
    }

    // Typing - switch to search mode
    if (input && !key.ctrl && !key.meta) {
      const newQuery = query + input
      setQuery(newQuery)
      const newResults = searchItems(newQuery, groups, root)
      resetCursor(newResults)
    }
  })

  const showBody = state === 'list' || state === 'search'

  return (
    <Box flexDirection="column">
      <Header
        state={isSearchMode && state === 'list' ? 'search' : state}
        query={query}
        selectedPath={selectedPath}
        errorMessage={errorMessage}
      />
      {showBody && (
        <>
          {isSearchMode ? (
            <SearchModeView
              items={searchResults}
              cursorIndex={cursorIndex}
              scrollOffset={scrollOffset}
              height={LIST_HEIGHT}
              query={query}
            />
          ) : (
            <ListModeView
              items={listItems}
              cursorIndex={cursorIndex}
              scrollOffset={scrollOffset}
              height={LIST_HEIGHT}
            />
          )}
          <Footer path={currentPath} noMatch={!selectableIndices.length} />
        </>
      )}
    </Box>
  )
}

// src/components/selector.vue
<script setup lang="ts">
import { Box, Text, useInput } from '@vue-tui/runtime'
import pc from 'picocolors'
import { computed, shallowRef } from 'vue'

import { toTildePath } from '../utils/format.ts'
import type { RepoGroup } from '../utils/repos.ts'
import { getMatchScore, searchReposByName } from '../utils/search.ts'

type SelectorState = 'list' | 'search' | 'succeed' | 'error'

interface ListItem {
  type: 'root' | 'owner' | 'repo' | 'blank'
  label: string
  path: string
  owner?: string
  selectable: boolean
}

interface SearchItem {
  type: 'project' | 'owner'
  label: string
  owner?: string
  path: string
  selectable: boolean
}

type SelectorItem = ListItem | SearchItem

interface SelectorProps {
  root: string
  groups: RepoGroup[]
  onSelect: (path: string) => void
  onCancel: () => void
}

defineOptions({
  name: 'Selector'
})

const { root, groups, onSelect, onCancel } = defineProps<SelectorProps>()

const LIST_HEIGHT = 15
const POINTER = '\u276F '
const POINTER_BLANK = '  '
const QUESTION = 'Where would you like to go? '

const state = shallowRef<SelectorState>('list')
const query = shallowRef('')
const cursorIndex = shallowRef(0)
const selectedPath = shallowRef('')
const errorMessage = shallowRef('')

const listItems = computed(() => buildListItems(root, groups))
const searchResults = computed(() => (query.value ? searchItems(query.value, groups, root) : []))
const isSearchMode = computed(() => query.value.length > 0)
const currentItems = computed<SelectorItem[]>(() =>
  isSearchMode.value ? searchResults.value : listItems.value
)
const selectableIndices = computed(() =>
  currentItems.value.map((item, i) => (item.selectable ? i : -1)).filter(i => i !== -1)
)
const scrollOffset = computed(() =>
  computeScroll(cursorIndex.value, currentItems.value.length, LIST_HEIGHT)
)
const currentPath = computed(() => {
  if (selectableIndices.value.length === 0) {
    return ''
  }
  return currentItems.value[cursorIndex.value]?.path || ''
})
const headerText = computed(() =>
  renderHeader(
    isSearchMode.value && state.value === 'list' ? 'search' : state.value,
    query.value,
    selectedPath.value,
    errorMessage.value
  )
)
const bodyLines = computed(() =>
  isSearchMode.value
    ? renderSearchLines(
        searchResults.value,
        cursorIndex.value,
        scrollOffset.value,
        LIST_HEIGHT,
        query.value
      )
    : renderListLines(listItems.value, cursorIndex.value, scrollOffset.value, LIST_HEIGHT)
)
const footerText = computed(() =>
  selectableIndices.value.length === 0
    ? pc.dim(pc.italic('No directory found'))
    : pc.dim('Path: ') + pc.gray(toTildePath(currentPath.value))
)
const showBody = computed(() => state.value === 'list' || state.value === 'search')

useInput((input, key) => {
  if (state.value === 'succeed' || state.value === 'error') {
    return
  }

  if (key.ctrl && input === 'c') {
    cancel()
    return
  }

  if (key.escape) {
    if (query.value) {
      query.value = ''
      resetCursor(listItems.value)
    } else {
      cancel()
    }
    return
  }

  if (key.return) {
    if (currentPath.value) {
      state.value = 'succeed'
      selectedPath.value = currentPath.value
      onSelect(currentPath.value)
    }
    return
  }

  if (key.upArrow) {
    moveCursor(-1)
    return
  }

  if (key.downArrow) {
    moveCursor(1)
    return
  }

  if (key.tab) {
    return
  }

  if (key.backspace || key.delete) {
    const newQuery = query.value.slice(0, -1)
    query.value = newQuery
    resetCursor(newQuery ? searchItems(newQuery, groups, root) : listItems.value)
    return
  }

  if (input && !key.ctrl && !key.meta) {
    const newQuery = query.value + input
    query.value = newQuery
    resetCursor(searchItems(newQuery, groups, root))
  }
})

function buildListItems(root: string, groups: RepoGroup[]): ListItem[] {
  const items: ListItem[] = [
    {
      type: 'root',
      label: '<root>',
      path: root,
      selectable: true
    }
  ]

  for (const group of groups) {
    items.push({ type: 'blank', label: '', path: '', selectable: false })
    items.push({
      type: 'owner',
      label: group.owner,
      path: group.path,
      owner: group.owner,
      selectable: true
    })

    for (const repo of group.repos) {
      items.push({
        type: 'repo',
        label: repo.name,
        path: repo.path,
        owner: group.owner,
        selectable: true
      })
    }
  }

  return items
}

function searchItems(queryText: string, groups: RepoGroup[], root: string): SearchItem[] {
  const q = queryText.toLowerCase()
  const items: SearchItem[] = []
  const projectMatches = searchReposByName(queryText, groups)
  const sortedProjects: SearchItem[] = projectMatches.map(match => ({
    type: 'project',
    label: match.repo.name,
    owner: match.repo.owner,
    path: match.repo.path,
    selectable: true
  }))
  const matchedOwners = new Set(projectMatches.map(match => match.repo.owner))

  if ('<root>'.includes(q)) {
    const rootScore = getMatchScore('<root>', queryText) ?? 3
    const rootItem: SearchItem = { type: 'project', label: '<root>', path: root, selectable: true }
    const insertIdx = sortedProjects.findIndex(
      (_, i) => (projectMatches[i]?.score ?? 3) > rootScore
    )
    if (insertIdx === -1) {
      sortedProjects.push(rootItem)
    } else {
      sortedProjects.splice(insertIdx, 0, rootItem)
    }
  }

  items.push(...sortedProjects)

  const ownerMatches: SearchItem[] = []
  for (const group of groups) {
    if (group.owner.toLowerCase().includes(q) || matchedOwners.has(group.owner)) {
      ownerMatches.push({
        type: 'owner',
        label: group.owner,
        path: group.path,
        selectable: true
      })
    }
  }

  if (ownerMatches.length > 0 && sortedProjects.length > 0) {
    items.push({
      type: 'owner',
      label: '',
      path: '',
      selectable: false
    })
  }

  items.push(...ownerMatches)
  return items
}

function highlightMatch(text: string, queryText: string, baseColor: (s: string) => string): string {
  if (!queryText) {
    return baseColor(text)
  }
  const lower = text.toLowerCase()
  const qLower = queryText.toLowerCase()
  const idx = lower.indexOf(qLower)
  if (idx === -1) {
    return baseColor(text)
  }

  const before = text.slice(0, idx)
  const match = text.slice(idx, idx + queryText.length)
  const after = text.slice(idx + queryText.length)
  return baseColor(before) + pc.bold(pc.green(match)) + baseColor(after)
}

function computeScroll(index: number, totalItems: number, height: number): number {
  if (totalItems <= height) {
    return 0
  }
  let start = index - Math.floor(height / 2)
  start = Math.max(0, start)
  return Math.min(start, totalItems - height)
}

function renderHeader(
  currentState: SelectorState,
  queryText: string,
  path: string,
  error: string
): string {
  if (currentState === 'succeed') {
    return `${pc.green('\u2713')} ${pc.bold(QUESTION)}${pc.cyan(toTildePath(path))}`
  }

  if (currentState === 'error') {
    return `${pc.red('\u2717')} ${pc.bold(pc.red(error))}`
  }

  return `${pc.yellow('?')} ${pc.bold(QUESTION)}${queryText}`
}

function renderListLines(
  items: ListItem[],
  index: number,
  offset: number,
  height: number
): string[] {
  const stickyOwner = getStickyOwner(items, offset, height)
  const adjustedHeight = stickyOwner ? height - 1 : height
  const displayStart = stickyOwner ? offset + 1 : offset
  const displayItems = items.slice(displayStart, displayStart + adjustedHeight)
  const lines: string[] = []

  if (stickyOwner) {
    const isSelected = items.indexOf(stickyOwner) === index
    const prefix = isSelected ? POINTER : POINTER_BLANK
    lines.push(prefix + pc.bold(pc.cyan(stickyOwner.label)))
  }

  for (let i = 0; i < displayItems.length; i++) {
    const item = displayItems[i]
    const actualIndex = displayStart + i
    const isSelected = actualIndex === index

    if (item.type === 'blank') {
      lines.push('')
      continue
    }

    const prefix = isSelected ? POINTER : POINTER_BLANK

    const text = isSelected
      ? pc.underline(pc.green(item.label))
      : item.type === 'owner'
        ? pc.bold(pc.cyan(item.label))
        : item.label
    lines.push(prefix + text)
  }

  return lines
}

function getStickyOwner(items: ListItem[], offset: number, height: number): ListItem | null {
  let stickyOwner: ListItem | null = null
  if (offset > 0) {
    for (let i = offset - 1; i >= 0; i--) {
      if (items[i].type === 'owner') {
        stickyOwner = items[i]
        break
      }
      if (items[i].type === 'blank' && i < offset) {
        break
      }
    }

    if (stickyOwner) {
      let groupEnd = items.indexOf(stickyOwner) + 1
      while (groupEnd < items.length && items[groupEnd].type !== 'blank') {
        groupEnd++
      }
      if (groupEnd <= offset) {
        stickyOwner = null
      }
    }
  }

  if (stickyOwner) {
    const ownerIdx = items.indexOf(stickyOwner)
    if (ownerIdx >= offset && ownerIdx < offset + height) {
      return null
    }
  }

  return stickyOwner
}

function renderSearchLines(
  items: SearchItem[],
  index: number,
  offset: number,
  height: number,
  queryText: string
): string[] {
  const visibleItems = items.slice(offset, offset + height)
  const lines: string[] = []

  for (let i = 0; i < visibleItems.length; i++) {
    const item = visibleItems[i]
    const actualIndex = offset + i
    const isSelected = actualIndex === index

    if (!item.selectable) {
      lines.push('')
      continue
    }

    const prefix = isSelected ? POINTER : POINTER_BLANK

    if (item.type === 'project') {
      const name = isSelected
        ? pc.underline(pc.green(item.label))
        : highlightMatch(item.label, queryText, s => s)
      const suffix = item.owner ? pc.dim(` (${item.owner})`) : ''
      lines.push(prefix + name + suffix)
    } else {
      const name = isSelected
        ? pc.underline(pc.green(item.label))
        : highlightMatch(item.label, queryText, pc.gray)
      lines.push(prefix + name)
    }
  }

  return lines
}

function moveCursor(direction: 1 | -1): void {
  if (selectableIndices.value.length === 0) {
    return
  }
  const currentSelIdx = selectableIndices.value.indexOf(cursorIndex.value)
  let nextSelIdx = currentSelIdx + direction
  if (nextSelIdx < 0) {
    nextSelIdx = selectableIndices.value.length - 1
  }
  if (nextSelIdx >= selectableIndices.value.length) {
    nextSelIdx = 0
  }
  cursorIndex.value = selectableIndices.value[nextSelIdx]
}

function resetCursor(items: { selectable: boolean }[]): void {
  const firstSelectable = items.findIndex(item => item.selectable)
  cursorIndex.value = Math.max(firstSelectable, 0)
}

function cancel(): void {
  state.value = 'error'
  errorMessage.value = 'Canceled.'
  onCancel()
}
</script>

<template>
  <Box flex-direction="column">
    <Text>{{ headerText }}</Text>
    <template v-if="showBody">
      <Text>{{ bodyLines.join('\n') }}</Text>
      <Box :margin-top="1">
        <Text>{{ footerText }}</Text>
      </Box>
    </template>
  </Box>
</template>
